In [1]:
import numpy as np

When there is no hidden layer, only input and output

In [2]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,0,0,1]]).T
x.shape, y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return (1/1+np.exp(-z))

In [4]:
def derivative_sig(z):
    return sig(z) * (1 - sig(z))

//Now, the range is from -1 to 1 with a shape of (2,1) 

In [5]:
#No hidden layer weights
weights =2 * np.random.random((2,1)) - 1  
bias = 2 * np.random.random(1) -1
weights, bias

(array([[-0.96669123],
        [ 0.55273142]]),
 array([0.50811881]))

In [6]:
#forward propogation with no hidden layer
output0 = x
output = sig(np.dot(output0, weights) + bias)
output

array([[1.60162629],
       [1.34616137],
       [2.58181421],
       [1.91013804]])

When there is one hidden layer

In [7]:
weights_hidden = 2 * np.random.random((2,2)) - 1
bias_hidden = 2 * np.random.random((1,2)) - 1
weights_output = 2 * np.random.random((2,1)) - 1
bias_output = 2 * np.random.random((1,1)) - 1

In [8]:
output_0 = x
output_hidden = sig(np.dot(output_0, weights_hidden) + bias_hidden)
output = sig(np.dot(output_hidden, weights_output) + bias_output)
output

array([[1.10858206],
       [1.0835356 ],
       [1.120745  ],
       [1.09465277]])

Backpropogation when there is no hidden layer